# Generated by Django 3.2.9 on 2021-11-28 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='hello',
        ),
    ]
