# Generated by Django 3.2.9 on 2021-11-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0003_goods_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='size',
        ),
        migrations.AddField(
            model_name='goods',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
