# Generated by Django 3.2.9 on 2021-12-11 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0004_auto_20211128_0423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name_plural': 'Goods'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='date',
        ),
    ]
