# Generated by Django 3.2.9 on 2021-12-11 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0005_auto_20211211_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='PhoneModel',
            field=models.ManyToManyField(to='shoppingmall.PhoneModel'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingmall.manufacturer'),
        ),
        migrations.AddField(
            model_name='goods',
            name='caseType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingmall.casetype'),
        ),
    ]
