# Generated by Django 3.2.9 on 2021-12-11 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0006_auto_20211211_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='caseType',
        ),
        migrations.AlterField(
            model_name='goods',
            name='PhoneModel',
            field=models.ManyToManyField(blank=True, to='shoppingmall.PhoneModel'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoppingmall.manufacturer'),
        ),
        migrations.DeleteModel(
            name='CaseType',
        ),
    ]
