# Generated by Django 3.2.9 on 2021-12-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0007_auto_20211211_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='delivery_fee',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
