# Generated by Django 3.2.9 on 2021-12-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0008_goods_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='delivery_fee',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
