# Generated by Django 3.2.9 on 2021-12-11 06:02

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0009_alter_goods_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
