# Generated by Django 3.2.9 on 2021-12-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='brief_content',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='address',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='contact',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='email',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='homepage',
            field=models.CharField(default=7, max_length=70),
            preserve_default=False,
        ),
    ]
