# Generated by Django 3.2.9 on 2021-12-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0013_auto_20211213_0430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casetype',
            options={},
        ),
    ]
