# Generated by Django 3.2.9 on 2021-12-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0016_auto_20211218_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='goods',
        ),
        migrations.AlterField(
            model_name='goods',
            name='delivery_fee',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(),
        ),
    ]
