# Generated by Django 3.2.9 on 2021-12-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingmall', '0018_auto_20211218_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='wish_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
